name: PullRequestAndMergeMaster
on:
  push:
    branches:
      - master
  pull_request:
    branches:
jobs:
  CreateAndPushWindowsExecutable:
    name: CreateAndPushWindowsExecutable
    strategy:
      matrix:
        go: [ 1.14 ]
        goarch: [ amd64 ]
    runs-on: windows-2019
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setting EnvVariable to checkout newLine char properly
      shell: bash
      run: |
        git config --system core.autocrlf false
        git config --system core.eol lf
    - name: Checking out the code
      uses: actions/checkout@v2
    - name: Test and Build
      shell: powershell
      run: |
        $ErrorView = 'NormalView'
        [Environment]::SetEnvironmentVariable("path", "$env:path;$env:GOPATH\bin", "Machine")
        .\win_build.ps1 -arch ${{ matrix.goarch }}
    - name: Set codeclimate prefix
      run: |
        echo "CC_PREFIX=$(go list -m)" >> $GITHUB_ENV
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ebf5d51be1de01e33b3b599496bf25286faa96afd50eacbf68207bd6211974a2
      with:
        coverageCommand: go test -coverprofile=c.out ./...
        prefix: ${{ env.CC_PREFIX }} # CC will strip this from the test report, leading to the correct file path
    - uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: .\target\bin\windows_${{ matrix.goarch }}