name: Snyk Dependencies
on:
  push:
    # Not enabled for PRs since github secrets are not available
    branches: [ master ]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        env:
          # snyk token, set trough github secrets
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          # snyk monitor run the tests and uploads the results in the corresponding page
          command: monitor